version: "3.7"
services:
  lib:
    tty: true
    build:
      context: .
      args:
        GITHUB_USER: "${GITHUB_USER}"
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
    volumes:
      - .:/wd
    ports:
      - "3001:3000"